export const SEARCH_ARTICLES = "SEARCH_ARTICLES";
export const HANDLE_SEARCH = "HANDLE_SEARCH";
export const SLIDER_CHANGE = "SLIDER_CHANGE";
export const FETCH_POSTS = "FETCH_POSTS";
export const FILTER_ARTICLES = "FILTER_ARTICLES";
export const SEND_WEATHER = "SEND_WEATHER";